### ISSUE TITLE
Move your code out of Microsoft hands

### ISSUE THREAD

**Issue by hhassey** [dessalines/referendum#27]
Hello dessalines, first of all, thanks for the amazing programs you are doing, I really like your work.

Do you plan on moving your repos out of github?

I am not a coder as good as you but I moved my repos to Gitlab, as a protest from the recent acquisition from Microsoft.

Regards.

hhassey

**Comment by dessalines** [comment]
I haven't developed this one in a long time, I abandoned it in favor of [simplevote](https://simplevote.tk). But I have all my code on gitlab as well: https://gitlab.com/dessalines
